export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOADED_EVENTS = 'LOADED_EVENTS';
export const LOAD_EVENTS = 'LOAD_EVENTS';
export const LOAD_ALL_EVENTS = 'LOAD_ALL_EVENTS';
export const LOADED_ALL_EVENTS = 'LOADED_ALL_EVENTS';
export const REGISTER_EVENT = 'REGISTER_EVENT';
export const EVENT_REGISTERED = 'EVENT_REGISTERED';
